#!/usr/bin/env groovy

pipeline {
   agent any
   stages {
       stage('Checkout') {
           steps {
               echo "Checking out the code now!"
               checkout([
                   $class: 'GitSCM',
                   branches: [[ name: '*/master' ]],
                   userRemoteConfigs: scm.userRemoteConfigs
               ])
           }
       }
       stage('Static Analysis') {
           steps {
               echo "Running Code Analsys Now!"
               sh 'rm -f clang-tidy-output.txt'
               sh 'clang-tidy -checks=\'*\' -p . src/*.cpp > clang-tidy-output.txt'
               recordIssues(
                   healthy: 1,
                   failOnError: true,
                   aggregatingResults: true,
                   enabledForFailure: true,
                   tool: [clangTidy(
                       pattern: 'clang-tidy-output.txt',
                       reportEncoding: 'UTF-8'
                   )]
               )  
           }
       }
       stage('CMake') {
           steps {
               echo "Running CMake now!"
               sh 'rm -rf cmake-build'
               sh 'mkdir -p cmake-build'
               dir('cmake-build') {
                   sh 'cmake ..'
               }
           }
       }
       stage('Build') {
           steps {
               echo "Building the app now!"
               dir('cmake-build') {
                   sh 'make install'
               }
           }
       }
   }
}
